### ISSUE TITLE
Add more options to define environment variables (global/project/step)

### ISSUE THREAD

**Issue by mowies** [jwplayer/buildpipe-buildkite-plugin#71]
It would be very cool to have an option to define environment variables on a global level and project level in the pipeline file.
Buildkite had that option in version 2 to have global env vars but they removed it in `v3` for some reason.

I have something in mind that could look like this:
```
projects:
  - label: project-xyz
    path: path/to/my/project
    env:
      THIS_IS_A_PROJECT_SCOPED_ENV_VAR: def456

env:
  - THIS_IS_A_PIPELINE_GLOBAL_ENV_VAR: abc123

steps:
  - label: ":docker: build - "
    command: echo "this is a build step"
    env:
      THIS_IS_A_STEP_SCOPED_ENV_VAR: xyz999

```

Buildpipe could already take care of the double dollar signs needed for some of those variables depending on where they are defined in the pipeline.
