### ISSUE TITLE
Specifying multiple branches in buildkite param won't render properly in pipeline

### ISSUE THREAD

**Issue by ksindi** [jwplayer/buildpipe-buildkite-plugin#9]
```
stairs:
  - name: foo
    scope: project
    buildkite:
      branches: "master develop feature"
      command: make foo
```

Above will render the branches part as:
```
steps:
  - branches: master develop feature  # should be wrapped in quotes
    command: make foo
```
